// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAB8bOO82HfCFsdEE5wPxHFc5MDZXxpfEw',
    appId: '1:368530559024:web:6ed90f20572e25940a5df5',
    messagingSenderId: '368530559024',
    projectId: 'flutter-application-7a708',
    authDomain: 'flutter-application-7a708.firebaseapp.com',
    storageBucket: 'flutter-application-7a708.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCChxgDDGhQNrraJ1eDbOxs6-PJKD05mLc',
    appId: '1:368530559024:android:7914354ddecb872c0a5df5',
    messagingSenderId: '368530559024',
    projectId: 'flutter-application-7a708',
    storageBucket: 'flutter-application-7a708.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2C13XUpJz97rWFa-cO7pvKktHEd1cjew',
    appId: '1:368530559024:ios:8574de1bf5d9525e0a5df5',
    messagingSenderId: '368530559024',
    projectId: 'flutter-application-7a708',
    storageBucket: 'flutter-application-7a708.appspot.com',
    iosClientId: '368530559024-vtu0cd5rncorgocgvlqrs6pr6fs4f2jj.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseclass',
  );
}
